### ISSUE TITLE
Nonce value is still using timestamp

### ISSUE THREAD

**Issue by kelvinwijaya** [GovTechSG/node-apex-api-security#19]
# Expected Behavior

Please describe the behavior you are expecting
Nonce is still using timestamp - to avoid different microservice unexpectedly generating the same nonce value

# Current Behavior

What is the current behaviour?
nonce is same as timestamp plus the padding

# Failure Information (for bugs)
N.A

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template and label it as **enhancement**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

N.A.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by robincher** [comment]
Hi @kelvinwijaya , do you mean edge scenario where services are generating the same nonce ?

**Comment by robincher** [comment]
PR #20  merged
