### ISSUE TITLE
Future browser support?

### ISSUE THREAD

**Issue by weijunyu** [GovTechSG/node-apex-api-security#23]
We may want to think about removing the nodejs specific parts and make this package browser ready - a file you can put in a <script> tag or at least import with webpack. This means using a third party crypto library and losing winston.

**Comment by robincher** [comment]
This would mean bundling the library using browserify and have an output where frontend or webpack can reference to?

**Comment by weijunyu** [comment]
Yep. Seems like browserify has a shim for the nodejs crypto library so that makes it even easier. If it can handle Winston then we don't need to change code at all

**Comment by weijunyu** [comment]
Yep. Seems like browserify has a shim for the nodejs crypto library so that makes it even easier. If it can handle Winston then we don't need to change code at all

**Comment by robincher** [comment]
@weijunyu Winston should not be the main deterrent since it's mainly for logging. We can think of alternative logging mechanism.

**Comment by weijunyu** [comment]
Without Winston it's good to go I think. Winston is meant for server side logging exclusively, don't think such a use case exists for the frontend.
Also this is a API signature library, logging should be delegated to higher level code. No reason for it to include a logging library at all imo

**Comment by robincher** [comment]
Let's aim to do this for next release. It should be capable of supporting webpack/frontend while maintaining it status as a node module
