### ISSUE TITLE
Typo in the index.js

### ISSUE THREAD

**Issue by Gyunikuchan** [GovTechSG/node-apex-api-security#3]
ApiSigningUtil : require('./lib/ApiSigning**Utill**')

should be

ApiSigningUtil : require('./lib/ApiSigning**Util**')

**Comment by robincher** [comment]
@Gyunikuchan Thanks for pointing out, will incorporate the fix in a jiffy.

**Comment by robincher** [comment]
Fix is incorporated in Pull Request #4
