### ISSUE TITLE
Move "test-suites-apex-api-security" to be in devDependencies rather than dependencies

### ISSUE THREAD

**Issue by Gyunikuchan** [GovTechSG/node-apex-api-security#34]
# Expected Behavior

The dependency in package.json: "test-suites-apex-api-security" should be a dev dependency instead.

# Current Behavior

When attempting to install the module on a docker image without git, the module will fail to install.

**Comment by robincher** [comment]
@Gyunikuchan thanks, let me look into that when i get back into office.
