### ISSUE TITLE
Input Object Mutation causing nonce and timestamp generation issues when rapidly generating tokens

### ISSUE THREAD

**Issue by Sylphias** [GovTechSG/node-apex-api-security#40]
# Expected Behavior
- Nonce and Timestamps generated per call on ApiSigningUtil.getSignatureToken() should be different on every call. When generating the nonce myself I can achieve this
![image](https://user-images.githubusercontent.com/5444382/65942230-6e981f00-e45f-11e9-97e8-d8cb656cda8f.png)

# Current Behavior
![image](https://user-images.githubusercontent.com/5444382/65941991-ed408c80-e45e-11e9-98aa-13159abae0d8.png)
Nonce values are the same if the function is called in succession with the same input. This should not be the case as the function itself should regenerate the nonce.

# Failure Information (for bugs)
The reason why this is happening is because it is mutating the input by adding a nonce to the input object. When the call is made again with the same object, a nonce will not be regenerated.

## Steps to Reproduce
I've written a sample app that demonstrates this issue
https://gist.github.com/Sylphias/04694239322a968f562ba982c6d6b022

**Comment by robincher** [comment]
Closed with PR #41
