### ISSUE TITLE
Side effects on the "formJson" field in ApiSigningUtil.js

### ISSUE THREAD

**Issue by Gyunikuchan** [GovTechSG/node-apex-api-security#5]
ApiSigningUtil.js: 136
`if (formJson != null) defaultParams = _.merge(formJson, defaultParams);`

The lodash merge function will cause a side effect on the formJson object itself, which is unexpected from the API user's side.

Would suggest that you do a lodash clone before the merge:
`if (formJson != null) defaultParams = _.merge(_.clone(formJson), defaultParams);`

**Comment by robincher** [comment]
Ok, will patch this during the next minor release. thanks @Gyunikuchan

**Comment by robincher** [comment]
Fix in PR #6
